version: '3.8'

services:
  vpn-server:
    build:
      context: .
      dockerfile: ./src/server/dockerfile
    container_name: vpn-server
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    ports:
      - "8080:8080/udp"
    restart: unless-stopped
    networks:
      - vpn-network
    sysctls:
      - net.ipv4.ip_forward=1

  vpn-client:
    build:
      context: .
      dockerfile: ./src/client/dockerfile
    container_name: vpn-client
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    depends_on:
      - vpn-server
    command: ["-server", "vpn-server", "-port", "8080"]
    restart: unless-stopped
    networks:
      - vpn-network
    sysctls:
      - net.ipv4.ip_forward=1

  vpn-client-2:
    build:
      context: .
      dockerfile: ./src/client/dockerfile
    container_name: vpn-client-2
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    depends_on:
      - vpn-server
    command: ["-server", "vpn-server", "-port", "8080"]
    restart: unless-stopped
    networks:
      - vpn-network
    sysctls:
      - net.ipv4.ip_forward=1
  
networks:
  vpn-network:
    driver: bridge