version: '3.8'

services:
  vpn-server:
    build:
      context: .
      dockerfile: cmd/Server-VPN/DockerFile
    container_name: vpn-server
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "8080:8080"
    networks:
      vpn-network:
        ipv4_address: 172.25.0.2

  vpn-client:
    build:
      context: .
      dockerfile: cmd/Client-VPN/DockerFile
    container_name: vpn-client
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - vpn-server
    environment:
      - SERVER_IP=172.25.0.2
      - SERVER_PORT=8080
    networks:
      vpn-network:
        ipv4_address: 172.25.0.3

networks:
  vpn-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16